const events = [
  {
    name: "Collibra Engineering Offsite",
    year: "2025",
    client: "Collibra",
    role: "Senior Executive Assistant / Event Producer",
    type: "Executive Summit",
    duration: "Annual",
    location: "TBD",
    budget: "$~250K",
    team: "3-4 producers",
    attendance: "100+ engineers",
    highlights: "Large-scale executive team offsite, logistical coordination across regions",
    keyAchievement: "Produced complex offsite with flawless execution",
    image: "https://via.placeholder.com/400x250?text=Collibra+Engineering+Offsite",
    tags: ["Executive Summit", "Team Building"]
  },
  {
    name: "Collibra Client Entertainment Events",
    year: "2025",
    client: "Collibra",
    role: "Senior Executive Assistant / Event Producer",
    type: "Client Event",
    duration: "Quarterly",
    location: "Various (NYC, SF, Boston, etc.)",
    budget: "$~50K-100K per event",
    team: "2-3 coordinators",
    attendance: "15-25 clients",
    highlights: "Strategic client dinners, executive relationship building, VIP experiences",
    keyAchievement: "Contributed to client relationship management and revenue impact",
    image: "https://via.placeholder.com/400x250?text=Client+Events",
    tags: ["Executive", "Client Relationship"]
  },
  {
    name: "Collibra PPT (Product Program Team) Planning",
    year: "2025",
    client: "Collibra",
    role: "Senior Executive Assistant",
    type: "Executive Summit",
    duration: "Bi-monthly",
    location: "New York",
    budget: "$~50K per event",
    team: "2+ coordinators",
    attendance: "40+ product leaders",
    highlights: "Large-scale executive summit coordination, cross-timezone logistics",
    keyAchievement: "Managed complex multi-location executive coordination",
    image: "https://via.placeholder.com/400x250?text=Product+Team+Planning",
    tags: ["Executive Summit"]
  },
  {
    name: "Collibra DCOT (Data Chief Officer Team) Offsites",
    year: "2025",
    client: "Collibra",
    role: "Senior Executive Assistant / Event Coordinator",
    type: "Executive Summit",
    duration: "Quarterly",
    location: "NYC and rotating",
    budget: "$~100K-150K per event",
    team: "2-3 coordinators",
    attendance: "15-20 executives",
    highlights: "Executive offsite planning, team bonding activities, strategic session facilitation",
    keyAchievement: "Successfully coordinated cross-functional executive alignment sessions",
    image: "https://via.placeholder.com/400x250?text=DCOT+Offsites",
    tags: ["Executive Summit", "Team Building"]
  },
  {
    name: "Collibra Executive Committee Meetings",
    year: "2025",
    client: "Collibra",
    role: "Senior Executive Assistant",
    type: "Executive Meeting",
    duration: "Weekly/bi-weekly",
    location: "New York / Virtual",
    budget: "N/A (internal)",
    team: "1-2 assistants",
    attendance: "20+ executives",
    highlights: "Meeting coordination, agenda development, action item tracking, executive support",
    keyAchievement: "Elevated ExCom operations from reactive to strategic; built coordination infrastructure",
    image: "https://via.placeholder.com/400x250?text=Executive+Committee",
    tags: ["Executive"]
  },
  {
    name: "Marrakesh Sales Incentive Trip",
    year: "2024",
    client: "Collibra",
    role: "Senior Executive Assistant / Event Producer",
    type: "Incentive Trip",
    duration: "4 days",
    location: "Marrakesh, Morocco",
    budget: "$~500K",
    team: "Destination management, luxury coordination",
    attendance: "60 top sales leaders",
    highlights: "Four Seasons accommodation, custom Agafay Desert party, curated luxury experiences",
    keyAchievement: "Orchestrated premium incentive trip with high retention impact; strong satisfaction from luxury-focused audience",
    image: "https://via.placeholder.com/400x250?text=Marrakesh+Trip",
    tags: ["Incentive Trip", "Luxury", "Travel"]
  },
  {
    name: "London CEO Dinner",
    year: "2024",
    client: "Collibra",
    role: "Senior Executive Assistant / Event Producer",
    type: "Executive Dinner",
    duration: "Evening",
    location: "London",
    budget: "$~150K",
    team: "Bespoke coordination",
    attendance: "15 senior clients",
    highlights: "Menu curation, strategic seating, executive briefings",
    keyAchievement: "Directly attributed to $4.9M in contract renewals; demonstrated ability to create experiences that drive measurable business outcomes",
    image: "https://via.placeholder.com/400x250?text=London+CEO+Dinner",
    tags: ["Executive Dinner", "Client Relationship"]
  },
  {
    name: "Prague Executive Summit",
    year: "2024",
    client: "Collibra",
    role: "Senior Executive Assistant / Event Program Manager",
    type: "Executive Summit",
    duration: "3 days",
    location: "Prague",
    budget: "$~350K (15% savings negotiated)",
    team: "Cross-functional, 60 C-level attendees",
    attendance: "60 senior leaders",
    highlights: "4.89/5.0 logistics score, strategic planning sessions + cultural experiences",
    keyAchievement: "Negotiated 15% hotel savings while maintaining luxury standards; balanced strategy work with team bonding",
    image: "https://via.placeholder.com/400x250?text=Prague+Summit",
    tags: ["Executive Summit", "Luxury"]
  },
  {
    name: "Fanatics Fest Apparel Product Launch",
    year: "2024",
    client: "Fanatics",
    role: "Event Program Manager",
    type: "Product Launch",
    duration: "Pre-event months + festival execution",
    location: "New York City",
    budget: "$~100K (product coordination)",
    team: "Cross-functional: retail, marketing, merchandising",
    attendance: "75K+ (festival)",
    highlights: "Aggregated sales data across Fanatics Retail, Mitchell & Ness, Lids; validated product line",
    keyAchievement: "First proprietary Fanatics Fest collection ranked #2 in sales across all major leagues; drove significant revenue",
    image: "https://via.placeholder.com/400x250?text=Fanatics+Apparel",
    tags: ["Product Launch", "Consumer Festival"]
  },
  {
    name: "WWE World at WrestleMania 2024",
    year: "2024",
    client: "Fanatics",
    role: "Event Program Manager",
    type: "Consumer Festival",
    duration: "Multi-day",
    location: "Las Vegas",
    budget: "$1,500,000+",
    team: "40+ leads",
    attendance: "30,000+",
    highlights: "5 simultaneous stages, 100+ talent, 60+ programs",
    keyAchievement: "Coordinated complex multi-stage operations with flawless execution and real-time troubleshooting",
    image: "https://via.placeholder.com/400x250?text=WWE+World",
    tags: ["Consumer Festival", "Entertainment"]
  },
  {
    name: "Fanatics Fest NYC 2024",
    year: "2024",
    client: "Fanatics",
    role: "Event Program Manager",
    type: "Consumer Festival",
    duration: "3 days",
    location: "New York City",
    budget: "$2,000,000",
    team: "40+ department heads",
    attendance: "75,000+",
    highlights: "3 stages, 200+ talent, 60+ programs, 95% on-time delivery",
    keyAchievement: "First proprietary Fanatics Fest apparel collection ranked #2 in sales across all major leagues",
    image: "https://via.placeholder.com/400x250?text=Fanatics+Fest+NYC",
    tags: ["Consumer Festival", "Large-Scale"]
  },
  {
    name: "Shopify Creator Team Events",
    year: "2020-2022",
    client: "Shopify",
    role: "Executive Personal Assistant / Event Producer",
    type: "Incentive/Team Event",
    duration: "Quarterly",
    location: "New York & various",
    budget: "$~50K-200K per event",
    team: "5+ producers",
    attendance: "50-500",
    highlights: "Creator celebration events, brand partnership activations, scalable run-of-show templates",
    keyAchievement: "Developed repeatable frameworks that standardized event execution across creator portfolio",
    image: "https://via.placeholder.com/400x250?text=Shopify+Events",
    tags: ["Team Building", "Brand Activation"]
  },
  {
    name: "Reese Cooper Brand Launch",
    year: "2021",
    client: "Shopify",
    role: "Executive Personal Assistant / Event Producer",
    type: "Pop-up Event",
    duration: "Evening",
    location: "New York City",
    budget: "$~200K",
    team: "8+ producers",
    attendance: "900+",
    highlights: "Designer collaboration, exclusive preview, influencer attendance",
    keyAchievement: "Strong event reception and media pickup for emerging designer brand",
    image: "https://via.placeholder.com/400x250?text=Reese+Cooper+Launch",
    tags: ["Pop-up Event", "Brand Launch"]
  },
  {
    name: "Victor Victor Pop-up + Launch Party",
    year: "2021",
    client: "Shopify",
    role: "Executive Personal Assistant / Event Producer",
    type: "Pop-up Event",
    duration: "2 days",
    location: "New York City",
    budget: "$~250K",
    team: "10+ producers",
    attendance: "1,000+",
    highlights: "A-list talent: Pharrell, Nigo, KAWS; 14K impressions, 3.1% engagement rate",
    keyAchievement: "Achieved +7% over foot traffic goal; generated strong media coverage and brand awareness",
    image: "https://via.placeholder.com/400x250?text=Victor+Victor",
    tags: ["Pop-up Event", "Celebrity", "Brand Launch"]
  },
  {
    name: "HiddenNY Brand Launch",
    year: "2020",
    client: "Shopify",
    role: "Executive Personal Assistant / Event Producer",
    type: "Pop-up Event",
    duration: "Evening",
    location: "New York City",
    budget: "$~180K",
    team: "8+ producers",
    attendance: "800+",
    highlights: "Curated designer brand showcase, VIP access, A-list attendees",
    keyAchievement: "Successful brand launch that strengthened creator partnerships",
    image: "https://via.placeholder.com/400x250?text=HiddenNY+Launch",
    tags: ["Pop-up Event", "Brand Launch"]
  },
  {
    name: "Narrativ Events & Operations",
    year: "2018-2020",
    client: "Narrativ",
    role: "Operations & Events Support",
    type: "Community",
    duration: "Ongoing",
    location: "New York",
    budget: "N/A (internal)",
    team: "2-3 core team",
    attendance: "Various",
    highlights: "Event production, team operations, stakeholder management",
    keyAchievement: "Contributed meaningfully with endless can-do attitude and exceptional organizational skills",
    image: "https://via.placeholder.com/400x250?text=Narrativ",
    tags: ["Community"]
  },
  {
    name: "All Tech Is Human Summit",
    year: "2018",
    client: "All Tech Is Human (David Ryan Polgar, Founder)",
    role: "Event Planner / Coordinator",
    type: "Conference",
    duration: "Full day",
    location: "ThoughtWorks Manhattan",
    budget: "$~100K",
    team: "3-5 producers",
    attendance: "400+",
    highlights: "Ethical tech summit with speakers, production issues resolved in real-time, crowd management",
    keyAchievement: "Praised as 'major reason the day went smoothly' and 'must-have for any team'; demonstrated calm leadership under pressure",
    image: "https://via.placeholder.com/400x250?text=Tech+Is+Human",
    tags: ["Conference", "Community"]
  },
  {
    name: "Gabriele & Debi Private Entertaining",
    year: "2012-2020",
    client: "Gabriele Corcos & Debi Mazar",
    role: "Executive Producer",
    type: "Private Events",
    duration: "Ongoing",
    location: "Brooklyn, NY",
    budget: "Various",
    team: "2-5 per event",
    attendance: "15-100",
    highlights: "100+ private events, brand partnerships, celebrity talent coordination",
    keyAchievement: "Successfully produced approximately 100 events over 8 years with consistent high quality",
    image: "https://via.placeholder.com/400x250?text=Private+Events",
    tags: ["Private Event", "Celebrity"]
  },
  {
    name: "Restaurant & Private Event Venue Operations",
    year: "2012-2020",
    client: "Gabriele Corcos & Debi Mazar",
    role: "Operations Manager",
    type: "Food & Beverage",
    duration: "8 years",
    location: "Brooklyn, NY",
    budget: "N/A (operational)",
    team: "20+ staff",
    attendance: "Daily events",
    highlights: "Staffing, licensing compliance, facilities management, budget oversight",
    keyAchievement: "Successfully managed brick-and-mortar venue operations while maintaining food standards and event execution",
    image: "https://via.placeholder.com/400x250?text=Venue+Operations",
    tags: ["Food & Beverage", "Operations"]
  },
  {
    name: "Future Bites",
    year: "2015-2016",
    client: "Gabriele Corcos & Debi Mazar (Celebrity Family Office)",
    role: "Executive Producer / Creative Director",
    type: "Streaming TV Show",
    duration: "Full series run",
    location: "New York",
    budget: "$~250K+",
    team: "Production team",
    attendance: "N/A (streaming)",
    highlights: "Food + tech + lifestyle exploration; professional production and talent coordination",
    keyAchievement: "Successfully developed and executed series concept with celebrity talent and premium production value",
    image: "https://via.placeholder.com/400x250?text=Future+Bites",
    tags: ["Media Production", "Food Festival"]
  },
  {
    name: "Counter Talk Live",
    year: "2014-2015",
    client: "Gabriele Corcos & Debi Mazar (Celebrity Family Office)",
    role: "Executive Producer / Creative Director",
    type: "Streaming TV Show",
    duration: "13-episode series, live-taped in Brooklyn",
    location: "Brooklyn, NY",
    budget: "$~300K+",
    team: "Full production crew",
    attendance: "N/A (streaming)",
    highlights: "First-of-its-kind live stream before social platforms had integrated functionality; SXSW presentation",
    keyAchievement: "Pioneered live streaming innovation; secured sponsorships and media consideration; instrumental in growing concept to full season",
    image: "https://via.placeholder.com/400x250?text=Counter+Talk",
    tags: ["Conference", "Media Production"]
  },
  {
    name: "Debi Mazar Photo Archive Project",
    year: "2015-2018",
    client: "Debi Mazar (actress/author memoir)",
    role: "Executive Producer / Archive Manager",
    type: "Creative Services",
    duration: "Ongoing",
    location: "New York",
    budget: "$~50K",
    team: "Solo project management",
    attendance: "N/A",
    highlights: "Cataloged decades of fashion and entertainment imagery in Adobe Lightroom; editorial selection for memoir",
    keyAchievement: "Managed substantial historical archive with meticulous tagging and organization for publication",
    image: "https://via.placeholder.com/400x250?text=Photo+Archive",
    tags: ["Community", "Creative Services"]
  },
  {
    name: "Saurette Children's Apparel Runway Show",
    year: "2008-2014",
    client: "Saurette (proprietary brand)",
    role: "Founder / Creative Director",
    type: "Fashion Show",
    duration: "Seasonal",
    location: "New York",
    budget: "$~50K per show",
    team: "3-5 stylists and producers",
    attendance: "200-400",
    highlights: "All styling and art direction for runway, seasonal lookbooks, marketing campaigns",
    keyAchievement: "Founded and ran children's apparel brand with consistent quality and professional presentation",
    image: "https://via.placeholder.com/400x250?text=Saurette+Show",
    tags: ["Fashion Show", "Pop-up Event"]
  },
  {
    name: "Macy's Private Label Product Development",
    year: "2002-2007",
    client: "Macy's",
    role: "Director of Product Development",
    type: "Retail Operations",
    duration: "5 years",
    location: "New York",
    budget: "$26M+ annual",
    team: "10+ design and production staff",
    attendance: "N/A (internal)",
    highlights: "Design-to-production cycle for private label; bi-annual Far East travel for sourcing",
    keyAchievement: "Managed significant private label business through full product lifecycle",
    image: "https://via.placeholder.com/400x250?text=Macys+Operations",
    tags: ["Retail Operations"]
  },
  {
    name: "Style & Co (May Company) Fashion Show",
    year: "2005-2010",
    client: "May Company (Style & Co brand)",
    role: "Director of Product Development / Show Producer",
    type: "Fashion Show",
    duration: "Semi-annual",
    location: "New York",
    budget: "$~35K per show",
    team: "5+ producers",
    attendance: "300-500",
    highlights: "$85M annual volume private label; professional runway presentations",
    keyAchievement: "Led design-to-sales cycle for major private label at massive scale",
    image: "https://via.placeholder.com/400x250?text=Style+Co+Show",
    tags: ["Fashion Show", "Retail"]
  },
  {
    name: "Saks Off 5th Fashion Show",
    year: "2005-2012",
    client: "Saks Off 5th",
    role: "Director of Product Development / Show Producer",
    type: "Fashion Show",
    duration: "Seasonal",
    location: "New York",
    budget: "$~40K per show",
    team: "5+ producers",
    attendance: "300-500",
    highlights: "Runway direction for seasonal private label collections",
    keyAchievement: "Consistently produced professional fashion shows for major retailer",
    image: "https://via.placeholder.com/400x250?text=Saks+Show",
    tags: ["Fashion Show", "Retail"]
  },
  {
    name: "MR Magazine Styling Shoots",
    year: "1990-1995",
    client: "MR Magazine",
    role: "Photo Stylist",
    type: "Media Production",
    duration: "Bi-monthly",
    location: "New York",
    budget: "$~3K per shoot",
    team: "2-3 per shoot",
    attendance: "Magazine circulation: 50K+",
    highlights: "Editorial styling, outfit curation, on-set creative direction",
    keyAchievement: "Regular contributor to prominent design magazine",
    image: "https://via.placeholder.com/400x250?text=MR+Magazine",
    tags: ["Media Production"]
  },
  {
    name: "Chicago Tribune Sunday Fashion Insert",
    year: "1991-1996",
    client: "Chicago Tribune",
    role: "Photo Stylist",
    type: "Media Production",
    duration: "Weekly",
    location: "Chicago, IL",
    budget: "N/A (editorial)",
    team: "2-3 per shoot",
    attendance: "Readership: 500K+",
    highlights: "Editorial styling, layout collaboration, on-set direction for weekly fashion coverage",
    keyAchievement: "Consistent editorial styling for major metropolitan newspaper",
    image: "https://via.placeholder.com/400x250?text=Chicago+Tribune",
    tags: ["Media Production", "Community"]
  },
  {
    name: "Marshall Field's Trunk Show Series",
    year: "1988-1990",
    client: "Marshall Field's",
    role: "Runway & Trunk Show Producer",
    type: "Pop-up Event",
    duration: "Monthly",
    location: "Chicago area",
    budget: "$~10K per show",
    team: "3-4 producers",
    attendance: "100-300",
    highlights: "Model coordination, styling direction, show logistics",
    keyAchievement: "Managed consistent series of retail events across multiple locations",
    image: "https://via.placeholder.com/400x250?text=Marshall+Fields",
    tags: ["Pop-up Event", "Retail"]
  },
  {
    name: "NY Pret Editorial Work",
    year: "1988-1992",
    client: "NY Pret",
    role: "Photo Stylist",
    type: "Media Production",
    duration: "Ongoing",
    location: "New York",
    budget: "Project-based",
    team: "2-3 per shoot",
    attendance: "Varies",
    highlights: "Trade show styling, special event production, magazine editorial",
    keyAchievement: "Established early career through consistent editorial work",
    image: "https://via.placeholder.com/400x250?text=NY+Pret",
    tags: ["Media Production"]
  }
];
