const events = [
  {
    name: "Fanatics Fest NYC 2024",
    year: "2024",
    client: "Fanatics",
    role: "Event Program Manager",
    type: "Consumer Festival",
    duration: "3 days",
    location: "New York City",
    budget: "$2,000,000",
    team: "40+ department heads",
    attendance: "75,000+",
    highlights: "3 stages, 200+ talent, 60+ programs, 95% on-time delivery",
    keyAchievement: "First proprietary Fanatics Fest apparel collection ranked #2 in sales across all major leagues",
    tags: ["Consumer Festival", "Large-Scale"]
  },
  {
    name: "WWE World at WrestleMania 2024",
    year: "2024",
    client: "Fanatics",
    role: "Event Program Manager",
    type: "Consumer Festival",
    duration: "Multi-day",
    location: "Las Vegas",
    budget: "$1,500,000+",
    team: "40+ leads",
    attendance: "30,000+",
    highlights: "5 simultaneous stages, 100+ talent, 60+ programs",
    keyAchievement: "Coordinated complex multi-stage operations with flawless execution and real-time troubleshooting",
    tags: ["Consumer Festival", "Entertainment"]
  },
  {
    name: "Prague Executive Summit",
    year: "2024",
    client: "Collibra",
    role: "Senior Executive Assistant / Event Program Manager",
    type: "Executive Summit",
    duration: "3 days",
    location: "Prague",
    budget: "$~350K (15% savings negotiated)",
    team: "Cross-functional, 60 C-level attendees",
    attendance: "60 senior leaders",
    highlights: "4.89/5.0 logistics score, strategic planning sessions + cultural experiences",
    keyAchievement: "Negotiated 15% hotel savings while maintaining luxury standards; balanced strategy work with team bonding",
    tags: ["Executive Summit", "Luxury"]
  },
  {
    name: "Marrakesh Sales Incentive Trip",
    year: "2024",
    client: "Collibra",
    role: "Senior Executive Assistant / Event Producer",
    type: "Incentive Trip",
    duration: "4 days",
    location: "Marrakesh, Morocco",
    budget: "$~500K",
    team: "Destination management, luxury coordination",
    attendance: "60 top sales leaders",
    highlights: "Four Seasons accommodation, custom Agafay Desert party, curated luxury experiences",
    keyAchievement: "Orchestrated premium incentive trip with high retention impact; strong satisfaction from luxury-focused audience",
    tags: ["Incentive Trip", "Luxury", "Travel"]
  },
  {
    name: "London CEO Dinner",
    year: "2024",
    client: "Collibra",
    role: "Senior Executive Assistant / Event Producer",
    type: "Executive Dinner",
    duration: "Evening",
    location: "London",
    budget: "$~150K",
    team: "Bespoke coordination",
    attendance: "15 senior clients",
    highlights: "Menu curation, strategic seating, executive briefings",
    keyAchievement: "Directly attributed to $4.9M in contract renewals; demonstrated ability to create experiences that drive measurable business outcomes",
    tags: ["Executive Dinner", "Client Relationship"]
  },
  {
    name: "Victor Victor Pop-up + Launch Party",
    year: "2021",
    client: "Shopify",
    role: "Executive Personal Assistant / Event Producer",
    type: "Pop-up Event",
    duration: "2 days",
    location: "New York City",
    budget: "$~250K",
    team: "10+ producers",
    attendance: "1,000+",
    highlights: "A-list talent: Pharrell, Nigo, KAWS; 14K impressions, 3.1% engagement rate",
    keyAchievement: "Achieved +7% over foot traffic goal; generated strong media coverage and brand awareness",
    tags: ["Pop-up Event", "Celebrity", "Brand Launch"]
  },
  {
    name: "HiddenNY Brand Launch",
    year: "2020",
    client: "Shopify",
    role: "Executive Personal Assistant / Event Producer",
    type: "Pop-up Event",
    duration: "Evening",
    location: "New York City",
    budget: "$~180K",
    team: "8+ producers",
    attendance: "800+",
    highlights: "Curated designer brand showcase, VIP access, A-list attendees",
    keyAchievement: "Successful brand launch that strengthened creator partnerships",
    tags: ["Pop-up Event", "Brand Launch"]
  },
  {
    name: "Reese Cooper Brand Launch",
    year: "2021",
    client: "Shopify",
    role: "Executive Personal Assistant / Event Producer",
    type: "Pop-up Event",
    duration: "Evening",
    location: "New York City",
    budget: "$~200K",
    team: "8+ producers",
    attendance: "900+",
    highlights: "Designer collaboration, exclusive preview, influencer attendance",
    keyAchievement: "Strong event reception and media pickup for emerging designer brand",
    tags: ["Pop-up Event", "Brand Launch"]
  },
  {
    name: "Counter Talk Live",
    year: "2014-2015",
    client: "Gabriele Corcos & Debi Mazar (Celebrity Family Office)",
    role: "Executive Producer / Creative Director",
    type: "Streaming TV Show",
    duration: "13-episode series, live-taped in Brooklyn",
    location: "Brooklyn, NY",
    budget: "$~300K+",
    team: "Full production crew",
    attendance: "N/A (streaming)",
    highlights: "First-of-its-kind live stream before social platforms had integrated functionality; SXSW presentation",
    keyAchievement: "Pioneered live str