const events = [
  {
    name: "Fanatics Fest NYC 2024",
    year: "2024",
    client: "Fanatics",
    role: "Event Program Manager",
    type: "Consumer Festival",
    duration: "3 days",
    location: "New York City",
    budget: "$2,000,000",
    attendance: "75,000+",
    teamSize: "40+",
    highlights: ["75K+ attendees", "3 simultaneous stages", "200+ talent coordinated", "$2M budget, zero overruns", "95% on-time programming"],
    quote: "FanaticsFest was the most complex logistics puzzle I've solved—and nailed it. 75K people, 3 stages, 200+ talent, zero audience chaos moments.",
    description: "Flagship consumer festival for collectibles fans featuring major talent (Travis Scott, Tom Brady, Spike Lee, Jalen Brunson, Josh Hart, Mike Tyson). Delivered on time and under budget despite supply chain challenges.",
    tags: ["Consumer Festival"],
    featured: true,
    photoLink: "https://drive.google.com/file/d/1JDo32K49uGxNuzeQ4nDiOZ3nCz93XeBD/view?usp=sharing",
    videoLink: "https://drive.google.com/file/d/1mFPj0znXt44O9bkcWOiUARAG52q8pmlW/view?usp=drive_link"
  },
  {
    name: "WWE World at WrestleMania 2024",
    year: "2024",
    client: "Fanatics",
    role: "Event Program Manager",
    type: "Consumer Festival",
    duration: "2 days",
    location: "Philadelphia, PA",
    budget: "$600,000",
    attendance: "35,000+",
    teamSize: "40+",
    highlights: ["35K+ attendees", "5 simultaneous stages", "100+ talent coordinated", "60+ programs delivered"],
    quote: "WWE World tested every skill. Multiple stages, celebrity egos, real-time decisions. Preparation enables handling anything.",
    description: "WWE-branded experience at WrestleMania featuring major wrestling talent (Rhea Ripley, Cody Rhodes, The Rock, Jey Uso, CM Punk). High-stakes event requiring flawless execution with multiple simultaneous stage operations.",
    tags: ["Consumer Festival"],
    featured: true,
    photoLink: "https://drive.google.com/file/d/1h8XtOEJ16iDhEcixNaJVpv0ZF8Z6hTMr/view?usp=drive_link",
    videoLink: "https://drive.google.com/file/d/1FOeG6XiZMH_ZhT-tXC_hOxW4d4LAssSS/view?usp=drive_link"
  },
  {
    name: "Prague Executive Summit",
    year: "2026",
    client: "Collibra",
    role: "Executive Assistant / Event Manager",
    type: "Executive Summit",
    duration: "3 days",
    location: "Prague, Czech Republic",
    budget: "$450,000",
    attendance: "60 senior leaders",
    teamSize: "8",
    highlights: ["4.89/5.0 logistics score", "15% hotel savings ($50K+)", "60 C-level attendees", "4 time zones coordinated"],
    quote: "Prague taught me executive events are about alignment, not logistics. People remember leaving strategically aligned.",
    description: "Executive summit for Collibra senior leaders at the Augustine Hotel in Prague. Balanced strategic planning sessions with cultural experiences. Negotiated 15% savings on hotel contracts while maintaining luxury standards.",
    tags: ["Executive Summit"],
    featured: true
  },
  {
    name: "Four Seasons Marrakesh Sales Incentive",
    year: "2026",
    client: "Collibra",
    role: "Executive Assistant / Event Manager",
    type: "Incentive Trip",
    duration: "3+ days",
    location: "Marrakesh, Morocco",
    budget: "$500,000",
    attendance: "60 top sales leaders",
    teamSize: "15",
    highlights: ["Custom Agafay Desert party", "Premium AI-enabled gifts", "Top 25 sales leaders + guests", "EMEA, APAC, NAMER regions"],
    quote: "Marrakesh meant saying to top performers: you matter enough for us to take this seriously. Desert party, cashmere, thoughtful details—that builds loyalty.",
    description: "Exclusive incentive trip for Collibra's top sales leaders. Featured Four Seasons Marrakesh with custom-built Agafay Desert party. Curated luxury experiences including traditional Moroccan hospitality and premium dining.",
    tags: ["Executive Summit"],
    featured: true
  },
  {
    name: "CEO Dinner — London Client Event",
    year: "2025",
    client: "Collibra",
    role: "Executive Assistant / Event Manager",
    type: "Client Dinner",
    duration: "1 evening",
    location: "London, England",
    budget: "$25,000",
    attendance: "15 senior clients",
    teamSize: "5",
    highlights: ["$4.9M ARR in contract renewals attributed", "Strategic seating facilitation", "World-class chef partnership", "Custom client gifting"],
    quote: "London dinner wasn't a dinner—$4.9M business conversation dressed as hospitality. That's high-touch events.",
    description: "High-impact CEO dinner for 15 senior clients in London. Owned menu curation, strategic seating to facilitate key business conversations, curated client gifts, and executive briefing materials.",
    tags: ["Executive Summit"],
    featured: true
  },
  {
    name: "Shopify × Victor Victor Popup + Launch Party",
    year: "2021",
    client: "Shopify",
    role: "Executive Assistant & Event Producer",
    type: "Pop-up Event",
    duration: "2 days",
    location: "NYC",
    budget: "$300,000",
    attendance: "1,000+",
    teamSize: "8",
    highlights: ["14K impressions", "3.1% engagement rate (1.1% over goal)", "+7% foot traffic over goal", "CPM $8.08 under target", "Pharrell, Nigo, KAWS as guests"],
    quote: "When celebrities want to post about your event, you've done something right.",
    description: "High-profile Victor Victor pop-up and launch party featuring Pharrell, Nigo, KAWS. Generated 14K social media impressions and strong press coverage.",
    tags: ["Pop-up Event"],
    featured: true,
    photoLink: "https://www.instagram.com/p/CbydyGvp6M2/",
    videoLink: "https://www.veed.io/view/c39fbf39-7357-41ca-9bd5-e6952322f982?panel=share",
    caseStudyLink: "https://103weup.com/2022/03/31/steven-victor-s-victor-victor-x-shopify-nyc-pop-lit-up-soho/"
  },
  {
    name: "Shopify × HiddenNY Popup",
    year: "2021",
    client: "Shopify",
    role: "Executive Assistant & Event Producer",
    type: "Pop-up Event",
    duration: "TBD",
    location: "NYC",
    budget: "$250,000",
    attendance: "500+",
    teamSize: "6",
    highlights: ["First HiddenNY popup", "Brand partnership activation", "Retail experience design", "Customer loyalty focus"],
    quote: "Best pop-ups make people feel like they discovered something they weren't supposed to find.",
    description: "First HiddenNY pop-up event produced for Shopify. Focused on brand partnership activation and customer engagement.",
    tags: ["Pop-up Event"],
    videoLink: "https://drive.google.com/file/d/1mdhMJMflCxajmk0XW2vrqQ5v14ywmgwX/view?usp=drive_link"
  },
  {
    name: "Shopify × Trinidad James Popup",
    year: "2021",
    client: "Shopify",
    role: "Executive Assistant & Event Producer",
    type: "Pop-up Event",
    duration: "TBD",
    location: "NYC",
    budget: "$100,000",
    attendance: "400+",
    teamSize: "6",
    highlights: ["Complex magazine press coverage", "Artist partnership", "Music & culture integration"],
    quote: "Organic artist partnerships beat forced brand activations.",
    description: "Trinidad James pop-up for Shopify featuring music and culture integration. Generated press coverage in Complex magazine.",
    tags: ["Pop-up Event"],
    photoLink: "https://drive.google.com/file/d/1cJslmIbi1tP9b-HaTkd1vnFYQuCxZ4JxZ1o/view"
  },
  {
    name: "Celebrity Family Office — Private Events",
    year: "2012–2020",
    client: "Gabriele Corcos & Debi Mazar",
    role: "Chief of Staff / Producer",
    type: "Private Events",
    duration: "8 years",
    location: "NYC",
    budget: "Varies",
    attendance: "100+ events",
    teamSize: "Varies",
    highlights: ["~100 high-profile private events", "8 years consistent excellence", "UHNWI experience standards", "Strict discretion maintained"],
    quote: "Best celebrity events: nobody outside guest list ever knows they happened.",
    description: "Produced and managed approximately 100 high-profile private events over 8 years for Celebrity Chef Gabriele Corcos and Actress Debi Mazar. Maintained strict confidentiality while delivering luxury experiences.",
    tags: ["Consumer Festival"],
    photoLink: "https://drive.google.com/file/d/1swCkFQUl5F13-ca4KZGotSudYSZtkA6b/view?usp=drive_link"
  },
  {
    name: "NYC Wine & Food Festival — Grand Tasting",
    year: "2017–2019",
    client: "NYCWFF / TKNY",
    role: "Event Producer",
    type: "Food Festival",
    duration: "2 days",
    location: "Piers 92/94, NYC",
    budget: "N/A",
    attendance: "5,000+",
    teamSize: "15",
    highlights: ["5,000+ attendees", "Multiple years executed", "Top chefs & wine producers", "Premium tasting experience"],
    quote: "Best tasting events make people feel inside industry, not watching from outside.",
    description: "Production on NYC Wine & Food Festival Grand Tasting at Piers 92/94. Large-scale food and beverage tasting with top chefs and wine producers.",
    tags: ["Food Festival"],
    featured: false,
    photoLink: "https://drive.google.com/file/d/12wTtXuna4tlcMM-wEAjoqLeUaoLi0-rp/view?usp=sharing"
  },
  {
    name: "Art of Cooking Gala",
    year: "2018–2019",
    client: "Sylvia Center",
    role: "Event Producer",
    type: "Benefit Gala",
    duration: "1 evening",
    location: "Hudson Mercantile, NYC",
    budget: "$500,000",
    attendance: "300+",
    teamSize: "10",
    highlights: ["300+ guests", "Top chef participation", "Auction coordination", "Fundraising success"],
    quote: "Successful benefit galas create emotional connection to cause—loosens purse strings.",
    description: "Art of Cooking Gala at Hudson Mercantile benefiting the Sylvia Center. Featured top chefs, auction elements, and gourmet experience.",
    tags: ["Benefit Gala"],
    photoLink: "https://drive.google.com/file/d/19zLbFw2b6ioCRkc7OVOX-NeXj6fxze8D/view?usp=sharing"
  },
  {
    name: "Latke Fest 2018",
    year: "2018",
    client: "Great Performances",
    role: "Event Producer",
    type: "Food Festival",
    duration: "1 day",
    location: "Brooklyn Museum, NY",
    budget: "$300,000",
    attendance: "2,000+",
    teamSize: "12",
    highlights: ["2,000+ attendees", "Museum venue partnership", "Vendor coordination at scale"],
    quote: "Food festivals create memorable food moments—everything else supports that.",
    description: "Latke Fest at Brooklyn Museum in partnership with Great Performances. Large-scale food festival featuring 2,000+ attendees and coordinated food vendors.",
    tags: ["Food Festival"],
    photoLink: "https://drive.google.com/file/d/1sO0e5h8JnXmUVlEzGCg5ZEa4VygBbGs5/view?usp=sharing"
  },
  {
    name: "All Tech Is Human 2018",
    year: "2018",
    client: "All Tech Is Human",
    role: "Event Producer",
    type: "Conference",
    duration: "2 days",
    location: "NYC + San Francisco",
    budget: "$250,000",
    attendance: "300+",
    teamSize: "8",
    highlights: ["Multi-city coordination", "Tech ethics focus", "Thought leadership platform"],
    quote: "Best tech events create community—people leave wanting to stay connected.",
    description: "All Tech Is Human conference produced in both NYC and San Francisco. Tech industry event focusing on ethical technology and human-centered design.",
    tags: ["Conference"],
    photoLink: "https://drive.google.com/file/d/1W0V0VTHS9E9z5FEk_-c2wLfJYqFaC-ZC/view?usp=sharing"
  },
  {
    name: "Future of Storytelling (FOST) 2018",
    year: "2018",
    client: "FOST",
    role: "Event Producer",
    type: "Conference",
    duration: "2 days",
    location: "Snug Harbor, Staten Island",
    budget: "N/A",
    attendance: "400+",
    teamSize: "8",
    highlights: ["400+ attendees", "Creative industry focus", "Media coverage"],
    quote: "Best conferences feel like conversations between smart people, not presentations at people.",
    description: "Future of Storytelling conference at Snug Harbor. Storytelling-focused conference for creative industry with speakers, panels, and networking.",
    tags: ["Conference"],
    videoLink: "https://vimeo.com/389745249",
    caseStudyLink: "https://previewmedia.com/our-work/future-of-storytelling"
  },
  {
    name: "Food Tank Summit",
    year: "2018",
    client: "Food Tank",
    role: "Event Producer",
    type: "Conference",
    duration: "1 day",
    location: "Vanderbilt Hall, NYC",
    budget: "N/A",
    attendance: "300+",
    teamSize: "8",
    highlights: ["Food systems focus", "Sustainability messaging", "Expert panels"],
    quote: "Best industry conferences educate while remaining genuinely engaging.",
    description: "Food Tank Summit at Vanderbilt Hall focusing on food sustainability. Coordinated expert panels, thought leaders, and industry engagement.",
    tags: ["Conference"]
  },
  {
    name: "Rule Breakers Event",
    year: "2018",
    client: "Bustle Media",
    role: "Event Producer",
    type: "Consumer Festival",
    duration: "1 day",
    location: "Prospect Park, NYC",
    budget: "N/A",
    attendance: "500+",
    teamSize: "8",
    highlights: ["Bustle community activation", "Media coverage", "Female empowerment focus"],
    quote: "Best media partnership events expand media brand, not replace it.",
    description: "Rule Breakers event for Bustle Media in Prospect Park celebrating bold women and culture change.",
    tags: ["Consumer Festival"],
    photoLink: "https://imgix.bustle.com/uploads/image/2018/9/23/5e906528-6a11-47c2-a5d8-417f18e4d83a-rule-breakers-event-cta.jpg"
  },
  {
    name: "Women in the World 2019",
    year: "2019",
    client: "Lincoln Center",
    role: "Event Producer",
    type: "Consumer Festival",
    duration: "3 days",
    location: "Lincoln Center, NYC",
    budget: "N/A",
    attendance: "800+",
    teamSize: "10",
    highlights: ["Premium venue", "Major speaker lineup", "Media coverage"],
    quote: "Best empowerment conferences: people leave believing change is possible.",
    description: "Women in the World conference at Lincoln Center. Major event on women's leadership and empowerment.",
    tags: ["Consumer Festival", "Conference"]
  },
  {
    name: "Harlem Eat UP 2019",
    year: "2019",
    client: "Various",
    role: "Event Producer",
    type: "Food Festival",
    duration: "2 days",
    location: "Morningside Park, NYC",
    budget: "N/A",
    attendance: "1,500+",
    teamSize: "8",
    highlights: ["1,500+ attendees", "Community partnership", "Cultural celebration"],
    quote: "Best park events feel like natural community gathering, not corporate activation.",
    description: "Harlem Eat UP 2019 at Morningside Park celebrating Harlem food culture with vendor coordination and community engagement.",
    tags: ["Food Festival", "Community Event"]
  },
  {
    name: "City Flavors NYCHA Event",
    year: "2018",
    client: "NYCHA",
    role: "Event Producer",
    type: "Community Event",
    duration: "1 day",
    location: "Highline Chelsea Piers Passageway, NYC",
    budget: "N/A",
    attendance: "400+",
    teamSize: "8",
    highlights: ["400+ attendees", "Public space activation", "Neighborhood cultural celebration"],
    quote: "Best community events: families attend and stay longer than planned.",
    description: "City Flavors event for NYCHA community celebrating neighborhood cultures at Highline Chelsea Piers Passageway.",
    tags: ["Community Event"]
  },
  {
    name: "NYC Food Waste Fair",
    year: "2017",
    client: "BK Expo",
    role: "Event Producer",
    type: "Community Fair",
    duration: "1 day",
    location: "BK Expo Center, Brooklyn",
    budget: "N/A",
    attendance: "1,000+",
    teamSize: "8",
    highlights: ["1,000+ attendees", "Sustainability education", "Community action focus"],
    quote: "Best sustainability events: people leave feeling empowered to change, not guilty about past.",
    description: "NYC Food Waste Fair at BK Expo Center. Food sustainability and waste reduction focused community fair.",
    tags: ["Community Event"],
    caseStudyLink: "https://www.foodwastefair.nyc/"
  },
  {
    name: "Northside Festival",
    year: "2017",
    client: "Wythe Hotel",
    role: "Event Producer",
    type: "Festival",
    duration: "2 days",
    location: "Wythe Hotel, Brooklyn",
    budget: "N/A",
    attendance: "1,000+",
    teamSize: "8",
    highlights: ["1,000+ attendees", "Artist coordination", "Brooklyn venue partnership"],
    quote: "Best festivals feel like a discovery—not a corporate event that happens to have music.",
    description: "Northside Festival production at Wythe Hotel. Music and culture festival with artist coordination and venue logistics.",
    tags: ["Consumer Festival"]
  },
  {
    name: "Charity Ball",
    year: "2016",
    client: "Duggal Greenhouse",
    role: "Event Producer",
    type: "Benefit Gala",
    duration: "1 evening",
    location: "Duggal Greenhouse, Brooklyn",
    budget: "N/A",
    attendance: "400+",
    teamSize: "6",
    highlights: ["400+ guests", "Fundraising success", "Premium venue"],
    quote: "Best charity events create both celebration and purpose.",
    description: "Charity Ball at Duggal Greenhouse. Benefit gala for charitable cause with high-net-worth donor engagement.",
    tags: ["Benefit Gala"],
    videoLink: "https://vimeo.com/84230460",
    caseStudyLink: "https://archive.charitywater.org/charityball/13/"
  },
  {
    name: "Downtown Brooklyn Colleges Fest",
    year: "2012",
    client: "BAM",
    role: "Event Producer",
    type: "Community Festival",
    duration: "1 day",
    location: "BAM Parking Lot, Brooklyn",
    budget: "N/A",
    attendance: "800+",
    teamSize: "6",
    highlights: ["800+ attendees", "College partnership", "Community access focus"],
    quote: "Best college fairs change somebody's trajectory.",
    description: "Downtown Brooklyn Colleges Fest at BAM introducing college options to students. Partnership with BAM and local colleges.",
    tags: ["Community Event"]
  },
  {
    name: "Fort Greene Festival",
    year: "2011",
    client: "Fort Greene Park",
    role: "Event Producer",
    type: "Community Festival",
    duration: "2 days",
    location: "Fort Greene Park, Brooklyn",
    budget: "N/A",
    attendance: "1,000+",
    teamSize: "6",
    highlights: ["1,000+ attendees", "Vendor activations", "Cultural programming"],
    quote: "Best community festivals: neighbors look forward to it every year.",
    description: "Fort Greene Festival at Fort Greene Park. Community celebration with vendor activations and cultural programming.",
    tags: ["Community Event"]
  },
  {
    name: "Collibra Board Meeting Production",
    year: "2025–2026",
    client: "Collibra",
    role: "Executive Assistant / Event Manager",
    type: "Board Event",
    duration: "1 day",
    location: "New York City & Amsterdam",
    budget: "$15,000",
    attendance: "Board members + executives",
    teamSize: "5",
    highlights: ["9-member C-Suite coordination", "Agenda development", "Pre-read management", "Key takeaway synthesis"],
    quote: "Best board meetings are invisible to the board—everything works because you anticipated every variable.",
    description: "Board meeting event support with agenda development, pre-read management, and synthesis of key takeaways for 9-member C-Suite.",
    tags: ["Executive Summit"]
  },
  {
    name: "Collibra Executive Offsite",
    year: "2026",
    client: "Collibra",
    role: "Executive Assistant / Event Manager",
    type: "Executive Meeting",
    duration: "2 days",
    location: "TBD",
    budget: "$50,000",
    attendance: "C-Suite + leadership",
    teamSize: "8",
    highlights: ["C-Suite alignment", "Strategic planning sessions", "Multi-timezone coordination"],
    quote: "Executive offsites: alignment happens here. Leave misaligned, logistics don't matter.",
    description: "Executive offsite for C-suite and leadership team featuring strategic planning, team bonding, and alignment sessions.",
    tags: ["Executive Summit"]
  },
  {
    name: "Collibra CEO Germany Client Trip",
    year: "2025",
    client: "Collibra",
    role: "Executive Assistant / Event Manager",
    type: "Executive Meeting",
    duration: "4 days",
    location: "Germany",
    budget: "N/A",
    attendance: "CEO + C-Suite",
    teamSize: "Varies",
    highlights: ["Bosch preferred vendor status secured", "Aldi Süd contract", "Multi-city itineraries", "Germany market expansion"],
    quote: "Strategic expansion isn't about deals—relationships built before, during, and after.",
    description: "International business development logistics for CEO's Germany market expansion. Coordinated multi-city itineraries, strategic briefings, and stakeholder meetings.",
    tags: ["Executive Summit"]
  },
  {
    name: "Future Bites — Podcast Production",
    year: "2012–2020",
    client: "Celebrity Family Office",
    role: "Chief of Staff / Producer",
    type: "Podcast Production",
    duration: "Ongoing",
    location: "NYC",
    budget: "Varies",
    attendance: "Hundreds per episode",
    teamSize: "10+",
    highlights: ["Regular episode schedule", "Growing audience", "Strong guest list"],
    quote: "",
    description: "Produced and managed Future Bites podcast with Chef Gabriele Corcos. Managed on-air logistics, talent coordination, content strategy.",
    tags: ["Consumer Festival"],
    photoLink: "https://drive.google.com/file/d/1taY0rRso9d5VCMiwg_GWp109UeIe1BzH/view?usp=sharing",
    videoLink: "https://drive.google.com/file/d/1gH7hm64J11wG_BhCBPx1cZggAzdPf9AF/view?usp=drive_link"
  },
  {
    name: "Counter Talk Live — Culinary Series",
    year: "2012–2020",
    client: "Celebrity Family Office",
    role: "Chief of Staff / Producer",
    type: "Live Event",
    duration: "Ongoing",
    location: "NYC",
    budget: "Varies",
    attendance: "Hundreds per episode",
    teamSize: "5+",
    highlights: ["Live-streamed series", "Content development", "Talent coordination"],
    quote: "",
    description: "Produced and managed live-streamed culinary series Future Bites featuring Chef Gabriele Corcos. Oversaw content development, talent coordination, and production logistics.",
    tags: ["Consumer Festival"],
    photoLink: "https://drive.google.com/file/d/1hOBkwlRU7UOUB1rlMFFJgyNqJrGwgX2Q/view?usp=sharing",
    videoLink: "https://drive.google.com/file/d/1azhjNfmZ4ttWwpgX1Rc_BJnAEj5DopMn/view?usp=drive_link"
  }
];
